name: David Cook
favicon: null
layout_spectrum: 0.05688
typography_spectrum: 0.86504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01b2b4'
    - '#7bdac4'
    - '#518183'
    - '#fefff8'
    - '#ada99d'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
